/* Generated by scripts/inject-env.mjs (development) — do not edit. Gitignored. */
export const devSecrets = {
  apiBaseUrl: "http://localhost:3000/api",
  supabaseUrl: "",
  supabaseAnonKey: "",
} as const;
